"""Port for verified installed model metadata and filesystem locations."""

from pathlib import Path
from typing import Callable, Protocol, Sequence

from smartvoice.domain.contracts import InstalledModel
from smartvoice.domain.models import ModelSpec


class ModelRepository(Protocol):
    def get_spec(self, model_id: str) -> ModelSpec: ...

    def installed_models(self) -> Sequence[InstalledModel]: ...

    def model_directory(self, model_id: str) -> Path: ...

    def catalog_models(self) -> Sequence[dict[str, object]]: ...

    def storage_summary(self) -> dict[str, int]: ...

    def install_model(self, model_id: str, progress: Callable[[int, int | None], None] | None = None) -> Path: ...

    def uninstall_model(self, model_id: str, *, loaded: bool = False) -> int: ...

    def export_model(self, model_id: str, destination: Path) -> Path: ...

    def import_model(self, archive_path: Path) -> Path: ...
