"""Focused streaming stage boundaries; native objects remain in adapters."""
from typing import Protocol, Callable, Mapping
from smartvoice.domain.streaming import AudioBlock, Hypothesis, TranslationResult, CommittedTarget, SynthesizedAudio

class ASRPort(Protocol):
    partial_support: bool
    plan: Mapping
    def push_audio(self, block: AudioBlock) -> list[Hypothesis]: ...
    def finish(self) -> list[Hypothesis]: ...
    def close(self) -> None: ...

class FormattingPort(Protocol):
    plan: Mapping
    def format(self, text: str, language: str, final: bool=False) -> str: ...
    def close(self) -> None: ...

class TranslationPort(Protocol):
    plan: Mapping
    def translate(self, text: str) -> TranslationResult: ...
    def stream(self, text: str, on_text: Callable[[str],None], cancelled: Callable[[],bool]) -> TranslationResult: ...
    def close(self) -> None: ...

class TTSPort(Protocol):
    def synthesize(self, target: CommittedTarget) -> SynthesizedAudio: ...
    def close(self) -> None: ...


class StageWorker(Protocol):
    async def construct(self, factory, *args, deadline=None): ...
    async def call(self, operation, *args, deadline=None, context=None): ...
    async def aclose(self): ...

class StageWorkerFactory(Protocol):
    def preflight(self, specs): ...
    def create(self, stage: str, profiler) -> StageWorker: ...
    def binding(self, spec, plan): ...

class ModelUseRepository(Protocol):
    def hold_models(self, model_ids): ...
    def get_spec(self, model_id: str): ...
    def installed_models(self): ...

class StageProfiler(Protocol):
    def add(self, name: str, seconds: float): ...
    def summary(self) -> Mapping: ...
